In [2]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from scipy.spatial import KDTree
import pickle

In [19]:
df = pd.read_csv('../data/merged_data.csv')

In [20]:
scaler = MinMaxScaler()

In [21]:
df.head()

artist_name                track_id  \
0          YG  2RM4jf1Xa9zPgMGRDiht8O   
1          YG  1tHDG53xJNGsItRA3vfVgs   
2       R3HAB  6Wosx2euFPMT14UXiWudMy   
3  Chris Cooq  3J2Jpw61sO7l6Hc7qdYV91   
4  Chris Cooq  2jbYvQCyPgX3CdmAzeVeuS   

                                       track_name  acousticness  danceability  \
0  Big Bank feat. 2 Chainz, Big Sean, Nicki Minaj      0.005820         0.743   
1                    BAND DRUM (feat. A$AP Rocky)      0.024400         0.846   
2                                   Radio Silence      0.025000         0.603   
3                                         Lactose      0.029400         0.800   
4                             Same - Original mix      0.000035         0.783   

   duration_ms  energy  instrumentalness  key  liveness  loudness  mode  \
0       238373   0.339             0.000    1    0.0812    -7.678     1   
1       214800   0.557             0.000    8    0.2860    -7.259     1   
2       138913   0.723             0.000    9    0.0824    -5.890     0   
3       125381   0.579             0.912    5    0.0994   -12.118     0   
4       124016   0.792             0.878    7    0.0332   -10.277     1   

   speechiness    tempo  time_signature  valence  popularity  
0       0.4090  203.927               4    0.118          15  
1       0.4570  159.009               4    0.371           0  
2       0.0454  114.966               4    0.382          56  
3       0.0701  123.003               4    0.641           0  
4       0.0661  120.047               4    0.928           0

In [22]:
df['track_id'][69]

'3Rx1zM3nDFQzAOYg9Hd0D4'

In [23]:
X = df.drop(['artist_name', 'track_id', 'track_name', 'duration_ms', 'popularity'], axis=1)
scaler.fit_transform(X)

array([[0.00584337, 0.74598394, 0.339     , ..., 0.81576347, 0.8       ,
        0.118     ],
       [0.02449799, 0.84939759, 0.557     , ..., 0.63607925, 0.8       ,
        0.371     ],
       [0.0251004 , 0.60542169, 0.723     , ..., 0.45989527, 0.8       ,
        0.382     ],
       ...,
       [0.06425703, 0.34437751, 0.487     , ..., 0.68491457, 0.8       ,
        0.365     ],
       [0.02931727, 0.3815261 , 0.399     , ..., 0.50323422, 0.6       ,
        0.105     ],
       [0.10140562, 0.8373494 , 0.517     , ..., 0.51976334, 0.8       ,
        0.193     ]])

In [24]:
model = KDTree(X)

In [26]:
result = model.query(df[df['track_id'] == '3Rx1zM3nDFQzAOYg9Hd0D4'].drop(['artist_name', 'track_id', 'track_name', 'duration_ms', 'popularity'], axis=1), k=11)

In [27]:
df[df['track_id'] == '3Rx1zM3nDFQzAOYg9Hd0D4']

artist_name                track_id         track_name  acousticness  \
69    Beatsole  3Rx1zM3nDFQzAOYg9Hd0D4  Shanti (ASOT 874)      0.000215   

    danceability  duration_ms  energy  instrumentalness  key  liveness  \
69         0.435       277098   0.796             0.887    2     0.407   

    loudness  mode  speechiness    tempo  time_signature  valence  popularity  
69   -12.252     1       0.0687  132.049               4    0.106          31

In [28]:
result[1][0][1:11]

array([115747, 115008,  73090,  20056,  22004,  92198,   3803, 115025,
        29916, 116963])

In [29]:
# This is a custom song with the audio features values below
result = model.query([[0.01, 0.5, 0.5, 0.1, 1, 0.1, -5, 1, 0.5, 190, 4, 0.5]], k=11)

In [30]:
result[1][0][1:]

array([ 98577,  37929,  89612,  70548,  83886, 110115,   7902,  34153,
       124521, 111037])

In [31]:
# See that the suggested IDs correspond to the IDs in the database
df.iloc[result[1][0][1:]]

artist_name                track_id  \
98577               Farruko  2VRVV7cvAGPJ2EBU4FIVCz   
37929        Kendrick Lamar  3m7B5vvKuFJ3gMARIzyKef   
89612               ShitKid  20OPqfLQ8U11ZdbxznG860   
70548   Kurt Hugo Schneider  0TO7NEjVQJtmPEyIVExFOo   
83886             GFMBRYYCE  3LILX3Peeirfb3NR5kfiyB   
110115              Wallows  6qMiZK4mGuCRkVwRFds4Sm   
7902                 Outlaw  22X23ozlTPi2j36tSG5LxS   
34153     The Lawrence Arms  3X6FAxvQlvnsHYbRTlxUnj   
124521              N.E.R.D  739vCwA3EpBSkk3uDsI2wB   
111037              Allie X  4P4nrjgbpghZ9oG3TaMV5n   

                          track_name  acousticness  danceability  duration_ms  \
98577                          Nadie      0.190000         0.679       228760   
37929                       ELEMENT.      0.223000         0.759       208733   
89612                Oh Me I'm Never      0.013500         0.498       177884   
70548          Just Give Me a Reason      0.061100         0.525       242211   
83886                        Lay Low      0.229000         0.692       151747   
110115                Let The Sun In      0.001410         0.320       223053   
7902    Renegade (feat. Demun Jones)      0.120000         0.670       206174   
34153   Chapter 13: The Hero Appears      0.000483         0.220       170018   
124521           Lemon - Drake Remix      0.000738         0.777       226107   
111037                    Paper Love      0.104000         0.566       197673   

        energy  instrumentalness  key  liveness  loudness  mode  speechiness  \
98577    0.617          0.000000    0    0.0798    -5.328     1       0.1200   
37929    0.700          0.000000    0    0.2310    -4.540     1       0.4730   
89612    0.804          0.006710    0    0.1480    -5.449     1       0.1190   
70548    0.866          0.000000    2    0.1180    -4.403     1       0.0845   
83886    0.845          0.000047    1    0.1600    -4.162     0       0.4750   
110115   0.663          0.000067    0    0.0968    -5.802     1       0.0291   
7902     0.942          0.000085    0    0.1370    -5.917     1       0.2680   
34153    0.923          0.000415    0    0.1850    -5.526     1       0.1040   
124521   0.657          0.000003    1    0.0932    -6.434     1       0.2370   
111037   0.684          0.001650    1    0.0683    -6.124     0       0.0752   

          tempo  time_signature  valence  popularity  
98577   189.993               4    0.665          82  
37929   189.991               4    0.483          20  
89612   189.935               4    0.166          19  
70548   190.029               4    0.309          31  
83886   190.011               4    0.576           3  
110115  189.891               4    0.673          56  
7902    190.083               4    0.626          37  
34153   190.744               4    0.576          17  
124521  189.992               4    0.245          70  
111037  189.873               4    0.330          40

In [32]:
pickle.dump(model, open('suggestion_model_2.pkl', 'wb'))

In [33]:
pickle.dump(scaler, open('scaler_2.pkl', 'wb'))