In [2]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from scipy.spatial import KDTree
import pickle

In [3]:
df = pd.read_csv('../data/merged_data.csv')

In [4]:
scaler = MinMaxScaler()

In [5]:
df.head()

artist_name                track_id  \
0          YG  2RM4jf1Xa9zPgMGRDiht8O   
1          YG  1tHDG53xJNGsItRA3vfVgs   
2       R3HAB  6Wosx2euFPMT14UXiWudMy   
3  Chris Cooq  3J2Jpw61sO7l6Hc7qdYV91   
4  Chris Cooq  2jbYvQCyPgX3CdmAzeVeuS   

                                       track_name  acousticness  danceability  \
0  Big Bank feat. 2 Chainz, Big Sean, Nicki Minaj      0.005820         0.743   
1                    BAND DRUM (feat. A$AP Rocky)      0.024400         0.846   
2                                   Radio Silence      0.025000         0.603   
3                                         Lactose      0.029400         0.800   
4                             Same - Original mix      0.000035         0.783   

   duration_ms  energy  instrumentalness  key  liveness  loudness  mode  \
0       238373   0.339             0.000    1    0.0812    -7.678     1   
1       214800   0.557             0.000    8    0.2860    -7.259     1   
2       138913   0.723             0.000    9    0.0824    -5.890     0   
3       125381   0.579             0.912    5    0.0994   -12.118     0   
4       124016   0.792             0.878    7    0.0332   -10.277     1   

   speechiness    tempo  time_signature  valence  popularity  
0       0.4090  203.927               4    0.118          15  
1       0.4570  159.009               4    0.371           0  
2       0.0454  114.966               4    0.382          56  
3       0.0701  123.003               4    0.641           0  
4       0.0661  120.047               4    0.928           0

In [6]:
df['track_id'][69]

'3Rx1zM3nDFQzAOYg9Hd0D4'

In [7]:
X = df.drop(['artist_name', 'track_id', 'track_name', 'popularity'], axis=1)
scaler.fit_transform(X)

array([[0.00584337, 0.74598394, 0.04194358, ..., 0.81576347, 0.8       ,
        0.118     ],
       [0.02449799, 0.84939759, 0.03773924, ..., 0.63607925, 0.8       ,
        0.371     ],
       [0.0251004 , 0.60542169, 0.02420446, ..., 0.45989527, 0.8       ,
        0.382     ],
       ...,
       [0.06425703, 0.34437751, 0.05737961, ..., 0.68491457, 0.8       ,
        0.365     ],
       [0.02931727, 0.3815261 , 0.07493985, ..., 0.50323422, 0.6       ,
        0.105     ],
       [0.10140562, 0.8373494 , 0.04229673, ..., 0.51976334, 0.8       ,
        0.193     ]])

In [8]:
model = KDTree(X)

In [9]:
result = model.query(df[df['track_id'] == '3Rx1zM3nDFQzAOYg9Hd0D4'].drop(['artist_name', 'track_id', 'track_name', 'popularity'], axis=1), k=11)

In [10]:
df[df['track_id'] == '3Rx1zM3nDFQzAOYg9Hd0D4']

artist_name                track_id         track_name  acousticness  \
69    Beatsole  3Rx1zM3nDFQzAOYg9Hd0D4  Shanti (ASOT 874)      0.000215   

    danceability  duration_ms  energy  instrumentalness  key  liveness  \
69         0.435       277098   0.796             0.887    2     0.407   

    loudness  mode  speechiness    tempo  time_signature  valence  popularity  
69   -12.252     1       0.0687  132.049               4    0.106          31

In [11]:
result[1][0][1:11]

array([111123, 126891,  50679,  44817, 101573, 116609,  42439,  87795,
        65046,  25414])

In [12]:
# This is a custom song with the audio features values below
result = model.query([[0.01, 0.5, 200000, 0.5, 0.1, 1, 0.1, -5, 1, 0.5, 190, 4, 0.5]], k=11)

In [17]:
result[1][0][1:]

array([ 25082, 112758,  19512,  20139,  63320,  15809, 102203,  77858,
        85571,  37241])

In [16]:
# See that the suggested IDs correspond to the IDs in the database
df.iloc[result[1][0][1:]]

artist_name                track_id             track_name  \
25082             Mountkid  1gRYSODTGjfufMdyu4Z3OV             No Lullaby   
112758            Illenium  20KW4L9nwQ5oP4IHHrbCeY  Sound of Where'd U Go   
19512          Deep Divers  5hKWeX4AmRMCNNBKxrD2AF        Dessous la mere   
20139                xKore  0NSIvT9r4OfHf1Iep3Msro              Get Ready   
63320       Omega Firebird  3OxM4vdtc2ZGGY0RYEl1sj            The Kingdom   
15809              T Model  1aTCeLCNbgKHVwXuYn6BUz        Sucker For Love   
102203        Rosie Carney  1gfzgfcrmkn2yTWuVGhCgh             Bud (Rose)   
77858   Михаил Шуфутинский  79IYu1KNWZd9zoz3isep2V            До свидания   
85571                Kunfu  0v0bbPylwszLuDBZ6yDpTM            Here I Come   
37241             Gera MXM  2IwpV2UAbLErksGyl6YGXz  Perdido Más No Muerto   

        acousticness  danceability  duration_ms  energy  instrumentalness  \
25082        0.17400         0.600       200000  0.9400          0.515000   
112758       0.00380         0.602       200000  0.7630          0.000144   
19512        0.69000         0.503       200000  0.4590          0.154000   
20139        0.00405         0.483       200000  0.9610          0.031700   
63320        0.46700         0.430       200000  0.0848          0.879000   
15809        0.63500         0.699       200000  0.5740          0.003630   
102203       0.99000         0.230       200000  0.0511          0.852000   
77858        0.32700         0.527       200002  0.8950          0.000000   
85571        0.00353         0.630       200000  0.4910          0.732000   
37241        0.72700         0.704       200000  0.8040          0.000000   

        key  liveness  loudness  mode  speechiness    tempo  time_signature  \
25082     6    0.2160    -3.428     1       0.0804  180.068               4   
112758    7    0.1020    -3.547     1       0.2700  180.004               4   
19512     9    0.1050    -9.966     0       0.0393  179.909               4   
20139     6    0.4480    -2.643     1       0.1700  174.068               4   
63320     8    0.1110   -19.154     1       0.0351  179.962               4   
15809    11    0.1030    -9.341     0       0.1110  174.092               4   
102203    6    0.3770   -25.311     1       0.0469  176.782               3   
77858     7    0.0526    -4.223     0       0.1250  165.877               4   
85571    11    0.2510   -10.795     0       0.0423  165.967               4   
37241    11    0.0866    -2.168     0       0.2780  163.857               4   

        valence  popularity  
25082    0.8710          35  
112758   0.2340          55  
19512    0.4320          46  
20139    0.3610          21  
63320    0.3280           4  
15809    0.4760           1  
102203   0.0483          67  
77858    0.7860           7  
85571    0.4260          16  
37241    0.8850          53

In [18]:
pickle.dump(model, open('suggestion_model.pkl', 'wb'))